spring:
  application:
    name: VRAgentPdv
  datasource:
    url: jdbc:postgresql://localhost:5432/vragentpdvportal
    username: vruser
    password: vrpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    br.com.vrsoftware.vragentpdv: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG